apiVersion : apps/v1
kind: Deployment
metadata:
  name: "srnagarakscluster-7b6b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "srnagarakscluster-7b6b"
  template:
    metadata:
      labels:
        app: "srnagarakscluster-7b6b"
    spec:
      containers:
        - name: "srnagarakscluster-7b6b"
          image: "acrux.azurecr.io/srnagarakscluster"
          ports:
          - containerPort: 80